//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsuntoDBweb
{
    using System;
    using System.Collections.Generic;
    
    public partial class raportti_sukupuolijakauma
    {
        public string Sukupuoli { get; set; }
        public bool Omistusasunto { get; set; }
        public Nullable<int> Asukkaita { get; set; }
    }
}
