//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsuntoDBweb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sukupuoli
    {
        public Sukupuoli()
        {
            this.Henkilo = new HashSet<Henkilo>();
        }
    
        public int Avain { get; set; }
        public int Koodi { get; set; }
        public string Selite { get; set; }
    
        public virtual ICollection<Henkilo> Henkilo { get; set; }
    }
}
