//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsuntoDB_WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Henkilo
    {
        public int Avain { get; set; }
        public string Henkilonumero { get; set; }
        public string Etunimi { get; set; }
        public string Sukunimi { get; set; }
        public string Syntymaaika { get; set; }
        public int SukupuoliKoodi { get; set; }
        public Nullable<int> AsuntoAvain { get; set; }
    
        public virtual Asunto Asunto { get; set; }
        public virtual Sukupuoli Sukupuoli { get; set; }
    }
}
